- type: department
  id: Nomads
  name: department-Nomads
  description: department-Nomads-description
  color: "#a36156"
  roles:
    - Nomad

- type: department
  id: DepFrench
  name: department-French
  description: department-French-description
  color: "#6490ce"
  roles:
    - FrenchLord
    - FrenchKnight
    - FrenchSwordsman
    - FrenchSpearman
    - FrenchRanged
    - FrenchMedic

- type: department
  id: DepEnglish
  name: department-English
  description: department-English-description
  color: "#dc3f3f"
  roles:
    - EnglishLord
    - EnglishKnight
    - EnglishSwordsman
    - EnglishSpearman
    - EnglishRanged
    - EnglishMedic

- type: department
  id: DepGerman
  name: department-German
  description: department-German-description
  color: "#080101"
  roles:
    - GermanCaptain
    - GermanSergeant
    - GermanSubmachineGunner
    - GermanRifleman
    - GermanMachinegunner
    - GermanMedic

- type: department
  id: DepSoviet
  name: department-Soviet
  description: department-Soviet-description
  color: "#f80505"
  roles:
    - SovietCaptain
    - SovietSergeant
    - SovietSubmachineGunner
    - SovietRifleman
    - SovietMachinegunner
    - SovietMedic
