- type: job
  id: SovietCWCaptain
  name: job-name-civ-sovietcw-cpt
  faction: SovietCW
  originalName: Kapitan
  description: job-description-civ-sovietcw-cpt
  playTimeTracker: JobSovietCWCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  startingGear: SovietCWCaptainGear
  icon: "JobIconICpt"
  supervisors: job-supervisors-nobody
  special:
    - !type:AddComponentSpecial
      components:
        - type: RussianAccent
        - type: NpcFactionMember
          factions:
            - SovietCW
        - type: ShowSovietFactionIcons
          factionIcon: SovietFaction

- type: playTimeTracker
  id: JobSovietCWCaptain

- type: startingGear
  id: SovietCWCaptainGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_officer_uniform
    outerClothing: civ13_suit_Soviet_officer_coat
    belt: civ13_pistol_Makarov_PM
    pocket2: civ13_magazine_PM_Makarov_magazine_(9x18mm)
    head: civ13_head_soviet_officer_cap
    pocket1: FlashlightLanternMilitary

# Sergeant

- type: job
  id: SovietCWSergeant
  originalName: Serzhant
  name: job-name-civ-sovietcw-sgt
  faction: SovietCW
  description: job-description-civ-sovietcw-sgt
  playTimeTracker: JobSovietCWSergeant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 5400 #1.5 hrs
  startingGear: SovietCWSergeantGear
  icon: "JobIconISgt"
  supervisors: job-supervisors-cpt
  special:
    - !type:AddComponentSpecial
      components:
        - type: RussianAccent
        - type: NpcFactionMember
          factions:
            - SovietCW
        - type: ShowSovietFactionIcons
          factionIcon: SovietFaction

- type: playTimeTracker
  id: JobSovietCWSergeant

- type: startingGear
  id: SovietCWSergeantGear
  equipment:
    shoes: civ13_shoes_leather_shoes_1
    jumpsuit: civ13_uniform_Soviet_uniform
    #outerClothing: civ13_suit_Soviet_coat
    head: civ13_head_soviet_pilotka
    belt: civ13_pistol_Makarov_PM
    pocket1: civ13_magazine_PM_Makarov_magazine_(9x18mm)
    pocket2: FlashlightLanternMilitary
  inhand:
    - civ13_ar_AK_74

# Assault Rifleman

- type: job
  id: SovietCWRifleman
  name: job-name-civ-sovietcw-rifleman
  faction: SovietCW
  originalName: Strelok
  description: job-description-civ-sovietcw-rifleman
  playTimeTracker: JobSovietCWRifleman
  startingGear: SovietCWRiflemanGear
  randomStartingGears: [SovietCWRiflemanGear, SovietCWRiflemanGear2]
  icon: "JobIconICpl"
  supervisors: job-supervisors-cpt
  special:
    - !type:AddComponentSpecial
      components:
        - type: RussianAccent
        - type: NpcFactionMember
          factions:
            - SovietCW
        - type: ShowSovietFactionIcons
          factionIcon: SovietFaction

- type: playTimeTracker
  id: JobSovietCWRifleman

- type: startingGear
  id: SovietCWRiflemanGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    #outerClothing: civ13_suit_Soviet_coat_1
    head: civ13_head_soviet_helmet
#    belt: ClothingWebbingRussianRifleman
    pocket1: FlashlightLanternMilitary
    pocket2: Gauze
  inhand:
    - civ13_ar_AK_74

- type: startingGear
  id: SovietCWRiflemanGear2
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_amoeba_outfit
    gloves: ClothingHandsGlovesFingerless
#    belt: ClothingWebbingRussianRifleman
#    outerClothing: civ13_suit_Soviet_coat
    head: civ13_head_soviet_helmet
    pocket1: FlashlightLanternMilitary
    pocket2: Gauze
  inhand:
    - civ13_ar_AK_74

# Machinegunner

- type: job
  id: SovietCWMachinegunner
  name: job-name-civ-sovietcw-machinegunner
  faction: SovietCW
  originalName: Pulemyotchik
  description: job-description-civ-sovietcw-machinegunner
  playTimeTracker: JobSovietCWMachinegunner
  startingGear: SovietCWMachinegunnerGear
  randomStartingGears: [SovietCWMachinegunnerGear, SovietCWMachinegunnerGear2]
  icon: "JobIconMg"
  supervisors: job-supervisors-cpt
  special:
    - !type:AddComponentSpecial
      components:
        - type: RussianAccent
        - type: NpcFactionMember
          factions:
            - SovietCW
        - type: ShowSovietFactionIcons
          factionIcon: SovietFaction

- type: playTimeTracker
  id: JobSovietCWMachinegunner

- type: startingGear
  id: SovietCWMachinegunnerGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    gloves: ClothingHandsGlovesFingerless
#    belt: ClothingWebbingSovietMG
    #outerClothing: civ13_suit_Soviet_coat
    head: civ13_head_soviet_helmet
    pocket1: CombatKnife
    pocket2: Gauze
  inhand:
    - civ13_mg_RPD_machine_gun

- type: startingGear
  id: SovietCWMachinegunnerGear2
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_amoeba_outfit
    gloves: ClothingHandsGlovesFingerless
#    belt: ClothingWebbingSovietMG
#    outerClothing: civ13_suit_Soviet_coat_1
    head: civ13_head_soviet_ushanka_1
    pocket1: CombatKnife
    pocket2: Gauze
  inhand:
    - civ13_mg_RPD_machine_gun

# Medic

- type: job
  id: SovietCWMedic
  name: job-name-civ-sovietcw-medic
  faction: SovietCW
  originalName: Vrach
  description: job-description-civ-sovietcw-medic
  playTimeTracker: JobSovietCWMedic
  startingGear: SovietCWMedicGear
  icon: "JobIconMedic"
  supervisors: job-supervisors-cpt
  special:
    - !type:AddComponentSpecial
      components:
        - type: RussianAccent
        - type: NpcFactionMember
          factions:
            - SovietCW
        - type: ShowSovietFactionIcons
          factionIcon: SovietFaction

- type: playTimeTracker
  id: JobSovietCWMedic

- type: startingGear
  id: SovietCWMedicGear
  equipment:
    shoes: civ13_shoes_Soviet_sapogi_boots
    jumpsuit: civ13_uniform_Soviet_uniform
    #outerClothing: civ13_suit_Soviet_coat_1
    head: civ13_head_soviet_medical_helmet
    belt: ClothingSatchelMedicalMedsFilled
    back: ClothingBackpackDuffelFilled
    pocket1: FlashlightLanternMilitary
    pocket2: civ13_magazine_AK_74_magazine_(5.45x39mm)
  inhand:
    - civ13_ar_AK_74
